urdf_path: "./h1pro.urdf"
mesh_dir: "/home/kaslensu/workspace/Luminis/Assets/Robots/zerith_h1pro"
ee_joints: "left_wrist_pitch_joint"
ee_link: "left_wrist_pitch_link"
ee_type: "gripper"
base_link: "dipan_link"
arm_joints_name:
  [
    "left_shoulder_pitch_joint",
    "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint",
    "left_elbow_joint",
    "left_wrist_roll_joint",
    "left_wrist_yaw_joint",
    "left_wrist_pitch_joint",
  ]
gripper_joints_name: ["left_jaw_left_finger_joint", "left_jaw_right_finger_joint"]
save_gripper_joints_name:
  ["left_jaw_left_finger_joint", "left_jaw_right_finger_joint"]
gripper_move:
  base: "left_jaw_left_finger_joint"
  mimic: [["left_jaw_right_finger_joint", -1.0, 0.0]]
  sign: 1
gripper_bias: 0.102
gripper_scale: [-0.04, 0.0]
delta_matrix: [[1,0,0],[0,1,0],[0,0,1]]
global_trans_matrix: [[1,0,0],[0,-1,0],[0,0,-1]]
dual_arm: True
rotate_lim: [0.0, 1.0]
wrist_camera_link: "left_jaw_camera_link"
wrist_camera_type: "D435"
wrist_camera:
  position: [0.0, 0.0, 0.0]
  orientation: [0, 0, 0]
